### ISSUE TITLE
Showing minimap in World Shader fails with AttributeError

### ISSUE THREAD

**Issue by josephclaytonhansen** [strike-digital/node_minimap#1]
Error text:

Python: Traceback (most recent call last):
  File "C:\Users\Joseph\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\node_minimap-0_0_3\operators.py", line 87, in modal
    if self.map_area:
  File "F:\blender\builds\3.1\scripts\modules\bpy_types.py", line 772, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'ModalDrawOperator' object has no attribute 'map_area'

location: <unknown location>:-1

**Comment by strike-digital** [comment]
Ah, thanks for reporting this, I've just committed a fix for it. Somehow I forgot to test the addon in the world shader, so thanks for pointing it out!

**Comment by josephclaytonhansen** [comment]
dang that was fast, thanks :) would you tag a release version for that bugfix? it's an active issue in the latest release tag so anyone downloading the "latest stable" isn't going to have the benefit of the bugfix
