### ISSUE TITLE
clicking on node in minimap causes TypeError

### ISSUE THREAD

**Issue by josephclaytonhansen** [strike-digital/node_minimap#2]
Text of error: 
Python: Traceback (most recent call last):
  File "C:\Users\Joseph\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\node_minimap-0_0_4\operators.py", line 161, in modal
    bpy.ops.view2d.pan((override), deltax=delta.x, deltay=delta.y)
  File "F:\blender\builds\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  VIEW2D_OT_pan.deltax expected an int type, not float

location: <unknown location>:-1

If I'm bothering you I can just make a fork and fix any bugs I can myself haha, I know my way around making an add-on

**Comment by strike-digital** [comment]
Ok, this one is fixed as well! Don't worry about bothering me lol, it's useful to be able to see what I've missed.
